In [1]:
import numpy as np

#   0.Summary:
    #A List looks like an Array, but it works more like a generic data structure.
    #An Numpy Array exists specifically to do math



#   1.Broadcasting in Numpy
    #A + np.array([4])


#   2.Plus operator is intelligent.
    #it broadcasts when you try to add a scalar.
    #if you add an array to an array, it does regular vector addition
    #A + np.array([4,5,6])


#   3.[2 * A] vs [2 * L]
    #in Numpy,  multiply operator does mathmatical operation
    #in List, multiply operator does repetition

In [28]:
L = [1,2,3]

A = np.array([1,2,3])


In [29]:
# List can be appended
L.append(4)

In [30]:
# Array is fixed, so you can't append it

A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
# Adding new element in list

L + [5]

[1, 2, 3, 4, 5]

In [ ]:
# Broadcasting in Numpy

A + np.array([4])

array([5, 6, 7])

In [ ]:
# plus operator is intelligent.
# it broadcasts when you try to add a scalar.
# if you add an array to an array, it does regular vector addition

A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
# you can't add vectors of different sizes

A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# in Numpy,  multiply operator does mathmatical operation
2 * A

array([2, 4, 6])

In [ ]:
# in List, multiply operator does repetition
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
# in List, "list + list" does repetition
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
# add 3 to each element in List

L2 = [e+3 for e in L]
print(L2)

[4, 5, 6, 7]


In [ ]:
# square each element in List

L2 = [e**2 for e in L]
print(L2)

[1, 4, 9, 16]


In [ ]:
# if you apply a function to a Numpy Array, it very often operates element-wise

print(A**2)
print(np.sqrt(A))
print(np.log(A))
print(np.exp(A))
print(np.tanh(A))

[1 4 9]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.76159416 0.96402758 0.99505475]
