# Summary

1.Numpy is easier to access element than List (Array[row,column] or Array[row][column])

2.in Numpy, a function is applied element-wisely

3.inverting a matrix is an inaccurate operation in PC, be careful!

4.if you input a matrix to np.diag, you will get a vector;
if you input a vector to np.diag, you will get a matrix

5.np.allclose function can tell whether two arrays are equal

In [1]:
import numpy as np

In [96]:
# Numpy is easier to access element than List


L = [[1,2],[3,4]]
print("List will not format output: ")
print(L)
print("#"*48)

A = np.array([[1,2],[3,4]])
print("Numpy will format output: ")
print(A)
print("#"*48)

print("in List, element needs to accessed by List[row][column]:")
print("L[0][1] = ",L[0][1])
print("L[0,1] will output error ")
print("L[:,1] will output error ")
print("#"*48)

print("in Numpy, element can be accessed by Array[row,column] or Array[row][column]:")
print("in Numpy, we can select the whole column by colon notation")
print("A[0,1] = ",A[0,1])
print("A[0][1] = ",A[0][1])
print("A[:,1] = ",A[:,1],"#colon notation")
print("#"*48)

print("in Numpy, we can transpose a matrix by A.T")
print(A.T)
print("#"*48)


List will not format output: 
[[1, 2], [3, 4]]
################################################
Numpy will format output: 
[[1 2]
 [3 4]]
################################################
in List, element needs to accessed by List[row][column]:
L[0][1] =  2
L[0,1] will output error 
L[:,1] will output error 
################################################
in Numpy, element can be accessed by Array[row,column] or Array[row][column]:
in Numpy, we can select the whole column by colon notation
A[0,1] =  2
A[0][1] =  2
A[:,1] =  [2 4] #colon notation
################################################
in Numpy, we can transpose a matrix by A.T
[[1 3]
 [2 4]]
################################################


In [44]:
print("in Numpy, a function is applied element-wisely, np.exp(A) output")
print(np.exp(A))
print("#"*48)

print("in List, numpy function treats it as if it were numpy array and output Array, np.exp(L) output")
print(np.exp(L))
print("#"*48)
print("if i want to pass some data into scikit-learn or matplotlib, there is no need to convert List into Array")

in Numpy, a function is applied element-wisely, np.exp(A) output
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
################################################
in List, numpy function treats it as if it were numpy array and output Array, np.exp(L) output
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
################################################
if i want to pass some data into scikit-learn or matplotlib, there is no need to convert List into Array


In [63]:
#matrix multiplication
B = np.array([[1,2,3],[4,5,6]])

print("A.dot(B) =")
print(A.dot(B))
print("#"*48)

print("np.linalg.det(A) =")
print(np.linalg.det(A))
print("#"*48)

print("np.linalg.inv(A) =")
print(np.linalg.inv(A))
print("#"*48)

print("np.linalg.inv(A).dot(A) =")
print(np.linalg.inv(A).dot(A))
print("inverting a matrix is an inaccurate operation in PC, be careful!")
print("#"*48)

print("np.trace(A) =")
print(np.trace(A))
print("#"*48)

A.dot(B) =
[[ 9 12 15]
 [19 26 33]]
################################################
np.linalg.det(A) =
-2.0000000000000004
################################################
np.linalg.inv(A) =
[[-2.   1. ]
 [ 1.5 -0.5]]
################################################
np.linalg.inv(A).dot(A) =
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
inverting a matrix is an inaccurate operation in PC, be careful!
################################################
np.trace(A) =
5
################################################


In [68]:
print("A = ")
print(A)
print("#"*48)

print("np.diag(A) = ")
print(np.diag(A))
print("#"*48)

print("np.diag([1,4]) = ")
print(np.diag([1,4]))
print("#"*48)

print("if you input a matrix to np.diag, you will get a vector")
print("if you input a vector to np.diag, you will get a matrix")


A = 
[[1 2]
 [3 4]]
################################################
np.diag(A) = 
[1 4]
################################################
np.diag([1,4]) = 
[[1 0]
 [0 4]]
################################################
if you input a matrix to np.diag, you will get a vector
if you input a vector to np.diag, you will get a matrix


In [95]:
# eigenvalue

print("np.linalg.eig(A) =")
print("")
print(np.linalg.eig(A))
print("")
print("np.linalg.eig(A) returns  [eigen value array] and  [matrix organized by eigenvectors]")
print("#"*48)
print("")


Lam, V = np.linalg.eig(A)
print("V[:,0]*Lam[0],  A.dot(V[:,0]) = ")
print(V[:,0]*Lam[0], A.dot(V[:,0]))
print("")
print("though they look the same, but they are not equal")
print("")
print("V[:,0]*Lam[0] == A.dot(V[:,0]) returns")
print(V[:,0]*Lam[0] == A.dot(V[:,0]))
print("")
print("Since PC don't have infinite memory, they can't have an infinite amount of precision")
print("number has been rounded off at some point")
print("")
print("np.allclose function can tell whether two arrays are equal")
print("np.allclose(V[:,0]*Lam[0], A.dot(V[:,0])) = ")
print(np.allclose(V[:,0]*Lam[0], A.dot(V[:,0])))




np.linalg.eig(A) =

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

np.linalg.eig(A) returns  [eigen value array] and  [matrix organized by eigenvectors]
################################################

V[:,0]*Lam[0],  A.dot(V[:,0]) = 
[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]

though they look the same, but they are not equal

V[:,0]*Lam[0] == A.dot(V[:,0]) returns
[ True False]

Since PC don't have infinite memory, they can't have an infinite amount of precision
number has been rounded off at some point

np.allclose function can tell whether two arrays are equal
np.allclose(V[:,0]*Lam[0], A.dot(V[:,0])) = 
True
