# Summary

1.[np.random.randn] can generate a matrix whose element come from normal distribution

2.[Matrix.mean(axis=0)] return columns' mean

3.[np.cov] by default treats each column as a vector observation, and we can solve this problem by transpose or rowvar

4.[np.random.choice] randomly selects items from a one dimensional input array

In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random((2,3))

array([[0.90756673, 0.5413645 , 0.39381664],
       [0.82091068, 0.51500448, 0.51284466]])

In [10]:
# what distribution do these random numbers come from

np.random.randn(2,3)
# randn does not accept a tuple as input for shape
# each dimension is passed in as a separate argument

array([[-0.08952808, -0.57163828,  0.55774041],
       [-1.22091677,  1.96754009, -0.54836866]])

In [20]:
R = np.random.randn(1000)
print("R.shape: ",R.shape)
print("R.mean(): ",R.mean())
print("R.var(): ",R.var())
print("R.std(): ",R.std())

R.shape:  (1000,)
R.mean():  0.037229429927148276
R.var():  0.9379755604050409
R.std():  0.9684913837536403


In [29]:
R = np.random.randn(1000,3)
print("R.shape: ",R.shape)
print("R.mean(axis=0): ",R.mean(axis=0))
print("R.mean(axis=0).shape: ",R.mean(axis=0).shape," , columns' mean")
print("R.mean(axis=1).shape: ",R.mean(axis=1).shape," , rows' mean")

R.shape:  (1000, 3)
R.mean(axis=0):  [-0.00936902 -0.02918972  0.01960478]
R.mean(axis=0).shape:  (3,)  , columns' mean
R.mean(axis=1).shape:  (1000,)  , rows' mean


In [37]:
# each row of matrix is a vector observation
# when you have vectors, the analog of variance is covariance

print("np.cov(R).shape: ",np.cov(R).shape)
print("cov by default treats each column as a vector observation")
print("the convention in ML needs to take each row as a vector observation")
print("")

print("solve this problem by transpose or rowvar")
print("np.cov(R.T)")
print(np.cov(R.T))
print("np.cov(R, rowvar=False)")
print(np.cov(R, rowvar=False))
print("")


np.cov(R).shape:  (1000, 1000)
cov by default treats each column as a vector observation
the convention in ML needs to take each row as a vector observation

solve this problem by transpose or rowvar
np.cov(R.T)
[[ 0.94689814 -0.02286447  0.03554041]
 [-0.02286447  0.90737464  0.00712447]
 [ 0.03554041  0.00712447  1.02531808]]
np.cov(R, rowvar=False)
[[ 0.94689814 -0.02286447  0.03554041]
 [-0.02286447  0.90737464  0.00712447]
 [ 0.03554041  0.00712447  1.02531808]]



In [40]:
# randomly generate integers

print("np.random.randint(0,10,size=(3,3))")
print(np.random.randint(0,10,size=(3,3)))

np.random.randint(0,10,size=(3,3))
[[0 4 8]
 [4 1 0]
 [1 7 8]]


In [41]:
# np.random.choice randomly selects items from a one dimensional input array

np.random.choice(10,size=(2,3))

array([[5, 6, 5],
       [7, 5, 8]])